"""add document error message and chunk position uniqueness

Revision ID: 743ce2f30300
Revises: 65f4c147a30e
Create Date: 2026-09-17 23:35:26.708374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '743ce2f30300'
down_revision: Union[str, Sequence[str], None] = '65f4c147a30e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_chunk_document_position', 'chunks', ['document_id', 'position'])
    op.add_column('documents', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'error_message')
    op.drop_constraint('uq_chunk_document_position', 'chunks', type_='unique')
    # ### end Alembic commands ###
